name: Test
on:
  push:
    # On any pull requests to $default-branch
    branches: ['master']

jobs:
  php-output:
    runs-on: ubuntu-latest
    name: "Files to lint"
    outputs:
      my-output: ${{ steps.set-output.outputs.php-files }}
    steps:
      - name: "Set Output"
        id: set-output
        run: echo "php-files=hello world" >> $GITHUB_OUTPUT


  php:
    runs-on: ubuntu-latest
    needs: [php-output]
    name: "PHP"
    steps:
      - name: "Use Output"
        run: echo "Output from previous job ${{ needs.php-output.outputs.my-output }}"
